### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by pankajumich** [SMLC-NYSBC/TARDIS#84]
Channels:
 - rrobert92
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides open3d needed by tardis-em-0.2.4-py311_0

Could not solve for environment specs
The following package could not be installed
└─ tardis-em is not installable because it requires
   └─ open3d, which does not exist (perhaps a missing channel).

**Comment by RRobert92** [comment]
Hi @pankajumich can you try installation with pip ? Conda/Mamba may need extra channel  -c open3d-admin
